CREATE TABLE AUTOINCRE(
ID INTEGER PRIMARY KEY NOT NULL,
TABELA VARCHAR(50),
SEQUENCIA INTEGER
);

create table CLIENTE(
ID INTEGER PRIMARY KEY NOT NULL,
NOME VARCHAR(50),
TELEFONE VARCHAR(20)
);

CREATE TABLE FORMA_PAGTO(
ID INTEGER PRIMARY KEY NOT NULL,
DESCRICAO VARCHAR(50)
);

CREATE TABLE FINANCEIRO(
ID INTEGER PRIMARY KEY NOT NULL,
NUMERO VARCHAR(20),
ORIGEM VARCHAR(50),
DATA_EMISSAO DATE,
DATA_VENCIMENTO DATE,
DATA_PAGAMENTO DATE,
ID_CLIENTE INTEGER,
FORMA_PAGTO INTEGER,
VALOR DECIMAL(10,2),
VALOR_PAGO DECIMAL(10,2),
PARCELADO VARCHAR(1),
PARCELAS INTEGER,
DOCORIGEM VARCHAR(20),
OBSERVACAO BLOB
);

ALTER TABLE FINANCEIRO ADD CONSTRAINT FK_FORMA_PAGTO FOREIGN KEY (FORMA_PAGTO) REFERENCES FORMA_PAGTO (ID);
ALTER TABLE FINANCEIRO ADD CONSTRAINT FK_ID_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID);


INSERT INTO AUTOINCRE VALUES('CLIENTE', 0, 1);
INSERT INTO AUTOINCRE VALUES('FORMA_PAGTO', 0, 2);
INSERT INTO AUTOINCRE VALUES('FINANCEIRO', 0, 3);