/*
	** VERSAO 2.0 **
	- Cadastro de produto
	- Cadastro de pedido
	- Controle de caixa
*/



INSERT INTO AUTOINCRE VALUES('PEDIDOS', 0, 5);
INSERT INTO AUTOINCRE VALUES('PRO_PEDIDO', 0, 6);
INSERT INTO AUTOINCRE VALUES('PRODUTO', 0, 7);

CREATE TABLE CONFIG(
CAIXAABERTO VARCHAR(1),
DATA_CAIXAABERTO TIMESTAMP,
COND_PAGTO_PEDIDO INTEGER,
MODULO_PEDIDO VARCHAR(1),
MODULO_FINANCEIRO VARCHAR(1)
);

CREATE TABLE PRODUTO(
ID INTEGER NOT NULL PRIMARY KEY,
DESCRICAO VARCHAR(100) NOT NULL,
ATIVO VARCHAR(1) NOT NULL,
VLR_UNITARIO DECIMAL(10,2) NOT NULL,
ESTOQUE DECIMAL(10,2)
);

CREATE TABLE PEDIDO(
ID INTEGER NOT NULL PRIMARY KEY,
NUMERO VARCHAR(10) NOT NULL,
DATA TIMESTAMP NOT NULL,
ID_CONDPAGTO INTEGER NOT NULL,
TOT_PRODUTO DECIMAL(10,2),
DESCONTO DECIMAL(10,2),
VLR_TOTAL DECIMAL(10,2)
);

CREATE TABLE PROD_PEDIDO(
ID INTEGER NOT NULL PRIMARY KEY,
ID_PEDIDO INTEGER NOT NULL,
ID_PRODUTO INTEGER NOT NULL,
VLR_UNITARIO DECIMAL(10,2),
QUANTIDADE DECIMAL(10,2),
VLR_TOTAL DECIMAL(10,2)
);

CREATE TABLE CONTA(
ID INTEGER NOT NULL PRIMARY KEY,
DESCRICAO VARCHAR(50)
);


CREATE TABLE MOVI_CONTA(
ID INTEGER NOT NULL PRIMARY KEY,
DATA TIMESTAMP NOT NULL,
ID_CONTA INTEGER NOT NULL,
ID_PEDIDO INTEGER,
HISTORICO VARCHAR(200) NOT NULL,
TIPO VARCHAR(1) NOT NULL,
VALOR DECIMAL(10,2) NOT NULL
);


ALTER TABLE PEDIDO ADD CONSTRAINT FK_COND_PAGTO FOREIGN KEY (ID_CONDPAGTO) REFERENCES FORMA_PAGTO (ID);
ALTER TABLE PROD_PEDIDO ADD CONSTRAINT FK_ID_PEDIDO FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO (ID) ON DELETE CASCADE;
ALTER TABLE PROD_PEDIDO ADD CONSTRAINT FK_ID_PRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO (ID);
ALTER TABLE MOVI_CONTA ADD CONSTRAINT FK_ID_CONTA FOREIGN KEY (ID_CONTA) REFERENCES CONTA (ID);
ALTER TABLE MOVI_CONTA ADD CONSTRAINT FK_ID_PEDIDO_CONTA FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO (ID);



